In [6]:
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd

In [9]:
TVD = int(input("Enter Depth(ft)"))
MW = float(input("Enter mud weight(ppg)"))              
Kick = float(input("Enter  kick(ppg)"))                
ID = float(input("Enter casing ID(inch)"))          
OD = float(input("Enter drill string OD(inch)"))    
V = float(input("Enter kick volume(bbl)"))

Enter Depth(ft)10000
Enter mud weight(ppg)12.5
Enter  kick(ppg)13
Enter casing ID(inch)8.5
Enter drill string OD(inch)5
Enter kick volume(bbl)10

In [22]:
df = pd.DataFrame({"Depth": range(TVD+1)})
df["HSP"] = 0.052*(MW)*(df["Depth"])              
df["FP"] = 0.052*(Kick)*(df["Depth"])              
df["SIDPP"] = df["FP"] - df["HSP"]                   
AC = ((ID**2)-(OD**2))/1029.4 
H = ((V*5.615)/(AC*5.615))
df["SICP"] = (df["FP"]-(0.052*H+0.052*12.5*(10000- H))) 
df.drop(0 ,axis=0)

       Depth      HSP        FP    SIDPP         SICP
1          1     0.65     0.676    0.026 -6369.042265
2          2     1.30     1.352    0.052 -6368.366265
3          3     1.95     2.028    0.078 -6367.690265
4          4     2.60     2.704    0.104 -6367.014265
5          5     3.25     3.380    0.130 -6366.338265
...      ...      ...       ...      ...          ...
9996    9996  6497.40  6757.296  259.896   387.577735
9997    9997  6498.05  6757.972  259.922   388.253735
9998    9998  6498.70  6758.648  259.948   388.929735
9999    9999  6499.35  6759.324  259.974   389.605735
10000  10000  6500.00  6760.000  260.000   390.281735

[10000 rows x 5 columns]